### Reorganzind Arrays

In [27]:
import numpy as np 
import sys

In [28]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after = before.reshape((1,8))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]]


In [29]:
# Vertically stacking Vectors 
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

# Normsal way
arr = np.vstack([v1, v2])
# Can amke multiple
arr2 = np.vstack([v1, v2,v1,v2])

print(arr)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [30]:
# Horizontal stack
h1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

arr = np.hstack([h1, v2])
print(arr)

[1 2 3 4 5 6 7 8]


## Misc3llaneous

Load Data from File

In [31]:
np.genfromtxt('data.txt', delimiter= ",")

ValueError: Some errors were detected !
    Line #5 (got 1 columns instead of 2)
    Line #6 (got 1 columns instead of 2)
    Line #9 (got 1 columns instead of 2)
    Line #10 (got 1 columns instead of 2)
    Line #11 (got 1 columns instead of 2)
    Line #12 (got 5 columns instead of 2)
    Line #13 (got 5 columns instead of 2)
    Line #15 (got 6 columns instead of 2)
    Line #18 (got 1 columns instead of 2)
    Line #19 (got 5 columns instead of 2)
    Line #20 (got 6 columns instead of 2)
    Line #21 (got 5 columns instead of 2)
    Line #22 (got 1 columns instead of 2)
    Line #23 (got 6 columns instead of 2)
    Line #26 (got 6 columns instead of 2)
    Line #29 (got 5 columns instead of 2)
    Line #31 (got 1 columns instead of 2)
    Line #32 (got 1 columns instead of 2)
    Line #35 (got 1 columns instead of 2)
    Line #36 (got 1 columns instead of 2)
    Line #37 (got 1 columns instead of 2)
    Line #38 (got 1 columns instead of 2)
    Line #39 (got 1 columns instead of 2)
    Line #40 (got 1 columns instead of 2)
    Line #41 (got 1 columns instead of 2)
    Line #44 (got 5 columns instead of 2)
    Line #46 (got 1 columns instead of 2)
    Line #49 (got 5 columns instead of 2)
    Line #50 (got 5 columns instead of 2)
    Line #52 (got 5 columns instead of 2)
    Line #54 (got 1 columns instead of 2)
    Line #55 (got 1 columns instead of 2)
    Line #56 (got 1 columns instead of 2)
    Line #57 (got 1 columns instead of 2)
    Line #58 (got 1 columns instead of 2)
    Line #59 (got 1 columns instead of 2)
    Line #60 (got 1 columns instead of 2)
    Line #61 (got 1 columns instead of 2)
    Line #62 (got 1 columns instead of 2)
    Line #63 (got 1 columns instead of 2)
    Line #64 (got 5 columns instead of 2)
    Line #65 (got 1 columns instead of 2)
    Line #67 (got 1 columns instead of 2)
    Line #68 (got 1 columns instead of 2)
    Line #69 (got 1 columns instead of 2)
    Line #70 (got 1 columns instead of 2)
    Line #71 (got 1 columns instead of 2)
    Line #72 (got 1 columns instead of 2)
    Line #73 (got 1 columns instead of 2)
    Line #74 (got 1 columns instead of 2)
    Line #75 (got 1 columns instead of 2)
    Line #76 (got 1 columns instead of 2)
    Line #77 (got 1 columns instead of 2)
    Line #78 (got 1 columns instead of 2)
    Line #79 (got 1 columns instead of 2)
    Line #80 (got 1 columns instead of 2)
    Line #81 (got 5 columns instead of 2)
    Line #82 (got 1 columns instead of 2)
    Line #83 (got 1 columns instead of 2)
    Line #84 (got 1 columns instead of 2)
    Line #85 (got 1 columns instead of 2)
    Line #87 (got 1 columns instead of 2)
    Line #88 (got 1 columns instead of 2)
    Line #89 (got 1 columns instead of 2)
    Line #90 (got 1 columns instead of 2)
    Line #91 (got 1 columns instead of 2)
    Line #92 (got 1 columns instead of 2)
    Line #93 (got 1 columns instead of 2)
    Line #94 (got 1 columns instead of 2)
    Line #95 (got 1 columns instead of 2)
    Line #96 (got 1 columns instead of 2)
    Line #97 (got 1 columns instead of 2)
    Line #98 (got 1 columns instead of 2)
    Line #99 (got 1 columns instead of 2)

![0]

[0]: dataFormat.png

this is for how to change this in an array 