In [2]:
import numpy as np 
import sys 

The Basics

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get dimensions
a.ndim

1

In [6]:
#Get shape 
b.shape

(2, 3)

In [7]:
#a.dtype
#get type
a.dtype

dtype('int64')

In [8]:
# get size
a.itemsize


8

In [9]:
a.size

3

In [10]:
#Get total size 
a.size * a.itemsize

24

In [11]:
# Get total bytes 2
a.nbytes

24

In [12]:
a.shape
print(a)

[1 2 3]


In [15]:
# Create a range from 0 to 9
c = np.arange(10)
c.shape

(10,)

The preceding statement creates a rank 1 array (one-dimensional) of ten ele-
ments. To get the shape of the array, use the shape property. Think of a1 as a
10×1 matrix.

You can also specify a step in the arange() function. The following code
snippet inserts a step value of 2:

In [22]:
c2 = np.arange(0,10,2)
print(c2)

[0 2 4 6 8]


create a NumPy array is to create it from a Python list as
follows:

In [23]:
list1 = [1,2,3,4,5] # list1 is a list in Python
r1 = np.array(list1) # rank 1 array
print(r1)

[1 2 3 4 5]


Accessing elements in the array is similar to accessing elements in a Python list:

In [25]:
print(r1[0])
print(r1[4])

1
5


The following code snippet creates another array named r2, which is
two-dimensional:

In [26]:
list2 = [6,7,8,9,0]
r2 = np.array([list1,list2])
# rank 2 array
print(r2)
'''
[[1 2 3 4 5]
[6 7 8 9 0]]

'''

[[1 2 3 4 5]
 [6 7 8 9 0]]


'\n[[1 2 3 4 5]\n[6 7 8 9 0]]\n\n'