Acessing/Changing specific elements, rows, columns,etc

In [29]:
import numpy as np
import sys

In [30]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14] ])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [31]:
# get a specific element [c,r]
a[1,5]
# get an entire row
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [32]:
#Get specific column
a[:, 2] 

array([ 3, 10])

In [33]:
#Getting a little fancy[startindex:endindex:stepsize]3.
a[1, 1:-1:-2]

array([], dtype=int64)

In [34]:
#Change number in array  
a[1,5] = 120
print(a)

[[  1   2   3   4   5   6   7]
 [  8   9  10  11  12 120  14]]


3-D exmaple

In [35]:
b = np.array([[[1,2], [3,4], [5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [36]:
# Get specific elements(work outside in)
b[0,1,1]
# firstArray:secondColumn:secondindex
# Use " : " to take the whole set

np.int64(4)

In [42]:
# replace
b[:,1,:] = [[91,8]] 

In [43]:
b

array([[[ 1,  2],
        [91,  8],
        [ 5,  6],
        [ 7,  8]]])

In [22]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14] ])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
