Acessing/Changing specific elements, rows, columns,etc

In [1]:
import numpy as np
import sys

In [2]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14] ])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [3]:
# get a specific element [c,r]
a[1,5]
# get an entire row
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [4]:
#Get specific column
a[:, 2] 

array([ 3, 10])

In [5]:
#Getting a little fancy[startindex:endindex:stepsize]3.
a[1, 1:-1:-2]

array([], dtype=int64)

In [6]:
#Change number in array  
a[1,5] = 120
print(a)

[[  1   2   3   4   5   6   7]
 [  8   9  10  11  12 120  14]]


3-D exmaple

In [7]:
b = np.array([[[1,2], [3,4], [5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [8]:
# Get specific elements(work outside in)
b[0,1,1]
# firstArray:secondColumn:secondindex
# Use " : " to take the whole set

np.int64(4)

In [9]:
# replace
b[:,1,:] = [[91,8]] 

In [10]:
b

array([[[ 1,  2],
        [91,  8],
        [ 5,  6],
        [ 7,  8]]])

In [11]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14] ])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
a1 = np.arange(10) # creates a range from 0 to 9
print(a1) # [0 1 2 3 4 5 6 7 8 9]
print(a1.shape) # (10,)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [13]:
a2 = np.arange(0,10,2) # creates a range from 0 to 9, step 2

print(a2) # [0 2 4 6 8

[0 2 4 6 8]


In [14]:
a6 = np.eye(4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
