In [2]:
import numpy as np 
import sys 

The Basics

In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [8]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [9]:
# Get dimensions
a.ndim

1

In [11]:
#Get shape 
b.shape

(2, 3)

In [14]:
#ad.type
#get type
a.dtype

dtype('int64')

In [17]:
# get size
a.itemsize


8

In [18]:
a.size

3

In [16]:
#Get total size 
a.size * a.itemsize

24

In [20]:
# Get total bytes 2
a.nbytes

24