Acessing/Changing specific elements, rows, columns,etc

In [2]:
import numpy as np
import sys

In [3]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14] ])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [4]:
# get a specific element [r, c]
a[1,5]
# get an entire row
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [5]:
#Get specific column
a[:, 2] 

array([ 3, 10])

In [6]:
#Getting a little fancy[startindex:endindex:stepsize]3.
a[1, 1:-1:-2]

array([], dtype=int64)

In [7]:
#Change number in array  
a[1,5] = 120
print(a)

[[  1   2   3   4   5   6   7]
 [  8   9  10  11  12 120  14]]


3-D exmaple

In [8]:
b = np.array([[[1,2], [3,4], [5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [11]:
# Get specific elements(work outside in)
b[0,1,1]
# firstArray:secondColumn:secondindex
# Use " : " to take the whole set

np.int64(4)

In [18]:
# replace
b[:,1,:] = [[9,9],[8,8]] 

ValueError: could not broadcast input array from shape (2,2) into shape (1,2)

In [21]:
b

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [22]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14] ])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
