Initialize Different Types Of Arrays

In [99]:
import numpy as np

In [100]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14] ])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [101]:
# all os matrix
np.zeros((2,3)) 
# following x,y,z rules of dimensions you can increase the dimension of the matrix 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [102]:
# All 1s matrix
np.ones((4,2,2), dtype='int32', order= 'C')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [103]:
# Any other number
np.full((2,2), 99, dtype= 'int64')

array([[99, 99],
       [99, 99]])

In [104]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [105]:
# Random decimal numbers
np.random.rand(2,4)
# Random decimals2
np.random.random_sample(a.shape)


array([[0.14121509, 0.93804442, 0.38415671, 0.26854258, 0.28230386,
        0.70879244, 0.0309787 ],
       [0.02845892, 0.84855294, 0.66682469, 0.73522678, 0.65369232,
        0.34333779, 0.118883  ]])

In [106]:
# Random integer numbers
np.random.randint(7, size= (3,3))

array([[6, 3, 6],
       [2, 2, 3],
       [0, 5, 5]])

In [107]:
# Identity matricss
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [108]:
# Repeat in an array
arr = np.array([1,2,3])
r1 = np.repeat(arr, 3, axis= 0)
print(r1)

print("next is 3D")

# Repeat in a 3d Array
arr2 = np.array([[1,2,]])
r1 = np.repeat(arr2, 3, axis= 0)
print(r1)

[1 1 1 2 2 2 3 3 3]
next is 3D
[[1 2]
 [1 2]
 [1 2]]


In [109]:
# add a number to an array 
arr2 = np.append(arr2, 3)
print(arr2)

[1 2 3]


In [135]:
# Practice matric
# Start bye making the array of one
arr3 = np.ones((5,5), dtype= 'int', order= 'C')
z = np.zeros((3,3))


# Then replacing with exclusives the middles way down 
arr3[1:-1, 1:-1]= z
arr3[2,2]= 9
print(z)
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# Be careful when copying arrays

In [148]:
a = np.array([1,2,3])
b= a.copy()
#  Changing the first element of 
b[0]= 7
print(b)

[7 2 3]
