### Reorganzind Arrays

In [27]:
import numpy as np 
import sys

In [28]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after = before.reshape((1,8))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]]


In [29]:
# Vertically stacking Vectors 
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

# Normsal way
arr = np.vstack([v1, v2])
# Can amke multiple
arr2 = np.vstack([v1, v2,v1,v2])

print(arr)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [30]:
# Horizontal stack
h1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

arr = np.hstack([h1, v2])
print(arr)

[1 2 3 4 5 6 7 8]


## Miscellaneous

Load Data from File

In [1]:
# np.genfromtxt('data.txt', delimiter= ",")

![0]

[0]: dataFormat.png

this is for how to change this in an array 