In [23]:
import numpy as np 
import sys 

The Basics

In [24]:
# To check the numpy version 
print(np.__version__)

2.2.4


In [25]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [26]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
# Get number ofdimensions
a.ndim

1

In [28]:
#Get shape 
b.shape

(2, 3)

In [29]:
#a.dtype
#get type
a.dtype

dtype('int64')

In [30]:
# get size
a.itemsize


8

In [31]:
a.size

3

In [32]:
#Get total size 
a.size * a.itemsize

24

In [33]:
# Get total bytes 2
a.nbytes

24

In [34]:
a.shape
print(a)

[1 2 3]


In [35]:
# Create a range from 0 to 9
c = np.arange(10)
c.shape

(10,)

The preceding statement creates a rank 1 array (one-dimensional) of ten elements. To get the shape of the array, use the shape property. Think of a1 as a 10×1 matrix.

You can also specify a step in the arange() function. The following code
snippet inserts a step value of 2:

In [36]:
c2 = np.arange(0,10,2)
print(c2)

[0 2 4 6 8]


create a NumPy array is to create it from a Python list as
follows:

In [37]:
list1 = [1,2,3,4,5] # list1 is a list in Python
r1 = np.array(list1) # rank 1 array
print(r1)

[1 2 3 4 5]


Accessing elements in the array is similar to accessing elements in a Python list:

In [38]:
print(r1[0])
print(r1[4])

1
5


The following code snippet creates another array named r2, which is
two-dimensional:

In [39]:
list2 = [6,7,8,9,0]
r2 = np.array([list1,list2])

# rank 2 array
print(r2)

'''
[[1 2 3 4 5]
[6 7 8 9 0]]

'''

[[1 2 3 4 5]
 [6 7 8 9 0]]


'\n[[1 2 3 4 5]\n[6 7 8 9 0]]\n\n'

### Check the amoumnt of dimentsino of an Array

In [40]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
d = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(a.ndim) # 0
print(b.ndim) # 1
print(c.ndim) # 3
print(d.ndim) # 2

0
1
3
2


Create an aray with 5 dimensions and verify that it has 5 dimensions

In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions:', arr.ndim) # 5 

[[1 2 3 4]]
number of dimensions: 2
